theme = "native"
icons = "awesome6"

[[block]]
block = "net"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}"

[[block]]
block = "sound"

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60
